namespace CinePosto.Domain.Tests.Parity;

/// <summary>Reads parity tables generated by the legacy code.</summary>
public static class TsvParityLoader
{
    /// <summary>Loads data rows from a tab-separated file, skipping the header line without trimming fields. Maps \N to null.</summary>
    public static IReadOnlyList<string?[]> Load(string fileName)
    {
        string path = Path.Combine(AppContext.BaseDirectory, "Parity", fileName);
        string[] lines = File.ReadAllLines(path);
        List<string?[]> rows = new(lines.Length);
        foreach (string line in lines.Skip(1))
        {
            string?[] fields = line.Split('\t');
            for (int i = 0; i < fields.Length; i++)
            {
                if (fields[i] == @"\N")
                {
                    fields[i] = null;
                }
            }

            rows.Add(fields);
        }

        return rows;
    }
}
